name: Pull Request CI

on:
  pull_request:
    paths:
      - '**.kt'
      - '**.xml'
      - '**.gradle'
      - '.github/workflows/pr-ci.yaml'

jobs:
  shared-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run test
        run: ./gradlew testDebugUnitTest

      - name: shared test report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: shared test
          path: shared/build/test-results/testDebugUnitTest/TEST-*.xml
          reporter: java-junit
          fail-on-error: false

      - name: mobile test report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: mobile test
          path: mobile/build/test-results/testDebugUnitTest/TEST-*.xml
          reporter: java-junit
          fail-on-error: false

      - name: wear test report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: wear test
          path: wear/build/test-results/testDebugUnitTest/TEST-*.xml
          reporter: java-junit
          fail-on-error: false
