name: Android Production Release CI

on:
  push:
    tags:
      - 'release*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      
      - name: Verify tags
        run: |
          LATEST_INTERNAL_TAG=$(git tag -l 'v*' | sort -V | tail -n 1)

          if [[ -z "$LATEST_INTERNAL_TAG" ]]; then
            echo "The internal release tag does not exist."
            exit 1
          fi

          if [[ "$(git rev-list -n 1 "$LATEST_INTERNAL_TAG")" != "$(git rev-parse HEAD)" ]]; then
            echo "The release tag does not point to the same commit as the latest internal release tag."
            exit 1
          fi

      - name: Notify Error to Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: workflow,job,commit,repo,ref,author
          username: GHA_PRODUCTION_RELEASE
          icon_emoji: ':pleading_face:'
          channel: '#android-app'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure()

      - name: build setup
        uses: ./.github/actions/shared-setup
        with:
          RUNNER_OS: ${{ runner.os }}
          GOOGLE_PLAY_SERVICE_JSON: ${{ secrets.GOOGLE_PLAY_SERVICE_JSON }}

      - name: Promote Artifact to Production
        run: bundle exec fastlane promote_internal_to_production

      - name: Notify Success to Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow # selectable (default: repo,message)
          username: GHA_RELEASE
          icon_emoji: ':sunglasses:'
          channel: '#android-app'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
