name: Android Release CI

on:
  release:
    types: [published]

env:
  ADMOB_KEY: ${{ secrets.ADMOB_KEY }}
  ADMOB_NATIVE_KEY: ${{ secrets.ADMOB_NATIVE_KEY }}
  GOOGLE_SERVICES_JSON: ${{ secrets.RELEASE_GOOGLE_SERVICES_JSON }}
  KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  GOOGLE_PLAY_SERVICE_JSON: ${{ secrets.GOOGLE_PLAY_SERVICE_JSON }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set config files
        run: echo $GOOGLE_SERVICES_JSON | base64 -d > mobile/src/release/google-services.json

      - name: Run Build
        run: ./gradlew :mobile:assembleRelease

      - name: Set publisher files
        run: echo $GOOGLE_PLAY_SERVICE_JSON | base64 -d > google-play-service.json

      - name: Run Release
        run: ./gradlew :mobile:publishBundle

      - name: Notify Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow # selectable (default: repo,message)
          username: GHA_RELEASE
          icon_emoji: ':sunglasses:'
          channel: '#wearlink'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
