name: Android Alpha Release CI

on:
  push:
    tags:
      - 'alpha*'

env:
  ADMOB_KEY: ${{ secrets.ADMOB_KEY }}
  ADMOB_NATIVE_KEY: ${{ secrets.ADMOB_NATIVE_KEY }}
  KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  GOOGLE_SERVICES_JSON: ${{ secrets.RELEASE_GOOGLE_SERVICES_JSON }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: build setup
        uses: ./.github/workflows/shared-setup.yaml
        secrets:
          GOOGLE_PLAY_SERVICE_JSON: ${{ secrets.GOOGLE_PLAY_SERVICE_JSON }}

      - name: Set config files
        run: |
          echo $GOOGLE_SERVICES_JSON | base64 -d > mobile/src/release/google-services.json
          echo $GOOGLE_SERVICES_JSON | base64 -d > wear/src/release/google-services.json

      - name: Run Build mobile
        run: ./gradlew :mobile:bundleRelease :wear:bundleRelease

      - name: Move mobile aab files
        run: |
          rm -rf build/app-bundles
          mkdir -p build/app-bundles
          mv mobile/build/outputs/bundle/release/mobile-release.aab build/app-bundles/.
          mv wear/build/outputs/bundle/release/wear-release.aab build/app-bundles/.

      - name: up play store
        run: bundle exec fastlane deploy_to_play_store

      - name: Notify Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow # selectable (default: repo,message)
          username: GHA_ALPHA_RELEASE
          icon_emoji: ':sunglasses:'
          channel: '#wearlink'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
