name: Android Alpha Release CI

on:
  push:
    tags:
      - 'alpha*'

env:
  RELEASE_JKS: ${{ secrets.RELEASE_JKS }}
  KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  GOOGLE_SERVICES_JSON: ${{ secrets.RELEASE_GOOGLE_SERVICES_JSON }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: build setup
        uses: ./.github/actions/shared-setup
        with:
          RUNNER_OS: ${{ runner.os }}
          GOOGLE_PLAY_SERVICE_JSON: ${{ secrets.GOOGLE_PLAY_SERVICE_JSON }}

      - name: Set config files
        run: |
          echo $RELEASE_JKS | base64 -d > release.jks
          echo $GOOGLE_SERVICES_JSON | base64 -d > mobile/src/release/google-services.json
          echo $GOOGLE_SERVICES_JSON | base64 -d > wear/src/release/google-services.json
      
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Build mobile
        run: ./gradlew :mobile:bundleRelease :wear:bundleRelease

      - name: Move mobile aab files
        run: |
          rm -rf build/app-bundles
          mkdir -p build/app-bundles
          mv mobile/build/outputs/bundle/release/mobile-release.aab build/app-bundles/.
          mv wear/build/outputs/bundle/release/wear-release.aab build/app-bundles/.

      - name: Copy changelogs
        run: |
            VERSION=$(tail -n 1 gradle.properties | sed -e 's/.*=//')
            if [ ! -f "fastlane/metadata/android/ja-JP/changelogs/2$VERSION.txt" ]; then
              cp -p fastlane/metadata/android/ja-JP/changelogs/1$VERSION.txt fastlane/metadata/android/ja-JP/changelogs/2$VERSION.txt
            fi

      - name: up play store
        run: bundle exec fastlane deploy_to_play_store

      - name: Notify Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow # selectable (default: repo,message)
          username: GHA_ALPHA_RELEASE
          icon_emoji: ':sunglasses:'
          channel: '#android-app'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
