name: Android Alpha Release CI

on:
  push:
    tags:
      - 'alpha*'

env:
  KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  GOOGLE_SERVICES_JSON: ${{ secrets.RELEASE_GOOGLE_SERVICES_JSON }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set config files
        run: |
          echo $GOOGLE_SERVICES_JSON | base64 -d > mobile/src/release/google-services.json
          echo $GOOGLE_SERVICES_JSON | base64 -d > wear/src/release/google-services.json
      
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Build mobile
        run: ./gradlew :mobile:assembleRelease :wear:assembleRelease

      - name: Move mobile apk files
        run: |
          rm -rf build/app-assembles
          mkdir -p build/app-assembles
          mv mobile/build/outputs/apk/release/mobile-release.apk build/app-assembles/.
          mv wear/build/outputs/apk/release/wear-release.apk build/app-assembles/.

      - name: up play store
        run: echo 'upload apk to server TODO'

      - name: Notify Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow # selectable (default: repo,message)
          username: GHA_ALPHA_RELEASE
          icon_emoji: ':sunglasses:'
          channel: '#wearlink'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
