name: Android Production Release CI

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Verify tags
        run: |
          LATEST_ALPHA_TAG=$(git tag -l 'alpha*' | sort -V | tail -n 1)
          LATEST_V_TAG=$(git tag -l 'v*' | sort -V | tail -n 1)

          if [[ "$GITHUB_REF" == refs/tags/v* ]]; then
            if [[ -z "$LATEST_ALPHA_TAG" || "$LATEST_V_TAG" != "$GITHUB_REF" ]]; then
              echo "The latest v tag is being pushed without the latest alpha tag or the alpha tag does not exist."
              exit 1
            fi
          fi

      - name: Notify Error to Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: workflow,job,commit,repo,ref,author
          username: GHA_PRODUCTION_RELEASE
          icon_emoji: ':pleading_face:'
          channel: '#wearlink'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure()

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set config files
        run: echo ${{ secrets.RELEASE_GOOGLE_SERVICES_JSON }} | base64 -d > google-play-service.json

      - name: Promote Artifact to Production
        run: |
          ./gradlew promoteArtifact --from-track alpha --promote-track production --release-status inProgress
          ./gradlew promoteArtifact --from-track wear:alpha --promote-track wear:production --release-status inProgress

      - name: Notify Success to Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow # selectable (default: repo,message)
          username: GHA_RELEASE
          icon_emoji: ':sunglasses:'
          channel: '#wearlink'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: success()
